import { baseLog, logEntry } from "../lib/log";

/**
 * Generic out-of-band callback collector.
 *
 * A tool plants a unique token in a payload and watches here for it to arrive.
 * A hit proves the target reached out — that a fetch tool ran, that a URL
 * parameter was dereferenced, that an injected instruction was followed. The
 * request that lands is the evidence, so everything about it is recorded.
 *
 * Token forms, in the order they are checked:
 *
 *   /oob/<token>              path form; works with the DNS that exists today
 *   /oob/<token>.gif          same, but answers with a 1x1 GIF so the callback
 *                             can ride in an <img> tag
 *   /oob?token=<token>        query form, for payloads that cannot carry a path
 *   <token>.hooks.<domain>    host form; needs a wildcard record, and is worth
 *                             adding because it fires on DNS resolution alone —
 *                             a target that can resolve but not egress still
 *                             shows up
 *
 * Storage is optional. With an OOB KV namespace bound, hits are queryable at
 * /oob/hits?token=<token>, which is what lets a scanner confirm a callback
 * without a human opening a dashboard. Without it the hit is still logged to
 * observability, and the query endpoint says so rather than returning an empty
 * list that reads like "no callback".
 */

export interface OobEnv {
  OOB?: KVNamespace;
}

/** Hits expire on their own; this is a test collector, not a log store. */
const HIT_TTL_SECONDS = 60 * 60 * 24 * 7;

/** Per-token cap. A target stuck in a retry loop must not fill the namespace. */
const MAX_HITS_PER_TOKEN = 50;

const MAX_BODY_PREVIEW = 2048;

/** Tokens are opaque and generated by the tool that plants them. */
const TOKEN_RE = /^[A-Za-z0-9_-]{4,128}$/;

/** 1x1 transparent GIF, for callbacks that have to look like an image. */
const PIXEL = Uint8Array.from([
  0x47, 0x49, 0x46, 0x38, 0x39, 0x61, 0x01, 0x00, 0x01, 0x00, 0x80, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x21, 0xf9, 0x04, 0x01, 0x00, 0x00, 0x00,
  0x00, 0x2c, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x01, 0x00, 0x00, 0x02, 0x02,
  0x44, 0x01, 0x00, 0x3b,
]);

/** Headers worth keeping. The rest is noise, and some of it is ours. */
const INTERESTING_HEADERS = [
  "user-agent",
  "referer",
  "origin",
  "x-forwarded-for",
  "x-forwarded-host",
  "x-real-ip",
  "content-type",
  "authorization",
  "cookie",
];

interface OobHit {
  ts: string;
  token: string;
  method: string;
  url: string;
  via: "path" | "query" | "host";
  ip: string;
  asn: number;
  country: string;
  colo: string;
  headers: Record<string, string>;
  query: Record<string, string>;
  body?: string;
}

function jsonResponse(data: unknown, status = 200): Response {
  return new Response(JSON.stringify(data, null, 2), {
    status,
    // Always JSON. Echoing a caller's content back as HTML would turn a
    // collector into an XSS gadget pointed at whoever opens the results.
    headers: { "Content-Type": "application/json", "Cache-Control": "no-store" },
  });
}

/**
 * extractToken finds the token and how it arrived, or null when this is not an
 * OOB request at all.
 */
function extractToken(url: URL): { token: string; via: OobHit["via"] } | null {
  const segments = url.pathname.split("/").filter(Boolean);
  if (segments[0] === "oob" && segments[1] && segments[1] !== "hits") {
    const token = segments[1].replace(/\.(gif|png|js|json|txt)$/i, "");
    if (TOKEN_RE.test(token)) return { token, via: "path" };
  }

  // The query form is confined to /oob. Accepting ?token= on any path would
  // swallow every other route the moment a payload happened to carry one —
  // /gitlab/scan.yml?token=abcd1234 would answer as a callback.
  if (segments[0] === "oob") {
    const q = url.searchParams.get("token") || url.searchParams.get("t");
    if (q && TOKEN_RE.test(q)) return { token: q, via: "query" };
  }

  // <token>.hooks.example.com — only meaningful once a wildcard record exists.
  //
  // The label count is what separates a planted token from the collector's own
  // hostname. hooks.mement0rq.com is three labels and its first one, "hooks",
  // matches the token pattern; treating that as a token would classify every
  // request to the site as a callback and answer JSON to all of them.
  const parts = url.hostname.split(".");
  if (parts.length >= 4 && TOKEN_RE.test(parts[0])) {
    return { token: parts[0], via: "host" };
  }
  return null;
}

async function buildHit(
  request: Request,
  url: URL,
  token: string,
  via: OobHit["via"]
): Promise<OobHit> {
  const cf = (request as unknown as Record<string, unknown>).cf as
    | Record<string, unknown>
    | undefined;

  const headers: Record<string, string> = {};
  for (const name of INTERESTING_HEADERS) {
    const value = request.headers.get(name);
    // Credentials that arrive here were sent by the target, and they are often
    // the point of the finding, so they are kept rather than stripped.
    if (value) headers[name] = value.slice(0, 512);
  }

  const query: Record<string, string> = {};
  url.searchParams.forEach((value, key) => {
    query[key] = value.slice(0, 512);
  });

  let body: string | undefined;
  if (request.method !== "GET" && request.method !== "HEAD") {
    try {
      body = (await request.text()).slice(0, MAX_BODY_PREVIEW);
    } catch {
      /* body already consumed or not readable */
    }
  }

  return {
    ts: new Date().toISOString(),
    token,
    method: request.method,
    url: url.toString().slice(0, 1024),
    via,
    ip: request.headers.get("CF-Connecting-IP") || "unknown",
    asn: Number(cf?.asn) || 0,
    country: String(cf?.country || "?"),
    colo: String(cf?.colo || "?"),
    headers,
    query,
    body,
  };
}

async function recordHit(env: OobEnv, hit: OobHit): Promise<boolean> {
  // Observability always gets it, so a hit is never lost just because storage
  // is not configured.
  logEntry({ ...hit, event: "oob_hit" } as never);

  if (!env.OOB) return false;

  const key = `hits:${hit.token}`;
  let hits: OobHit[] = [];
  try {
    hits = (await env.OOB.get<OobHit[]>(key, "json")) || [];
  } catch {
    hits = [];
  }
  hits.push(hit);
  if (hits.length > MAX_HITS_PER_TOKEN) {
    hits = hits.slice(-MAX_HITS_PER_TOKEN);
  }
  await env.OOB.put(key, JSON.stringify(hits), { expirationTtl: HIT_TTL_SECONDS });
  return true;
}

/**
 * handleOob answers collector and query requests. Returns null when the path
 * is not ours, so the caller can carry on routing.
 */
export async function handleOob(
  request: Request,
  env: OobEnv
): Promise<Response | null> {
  const url = new URL(request.url);
  const log = baseLog(request);

  // ── Query: did anything call back for this token? ──────────────
  if (url.pathname === "/oob/hits") {
    const token = url.searchParams.get("token") || "";
    if (!TOKEN_RE.test(token)) {
      return jsonResponse({ error: "pass ?token=<token>" }, 400);
    }
    if (!env.OOB) {
      // An empty list here would read as "nothing called back", which is the
      // one answer this endpoint must never give when it cannot know.
      return jsonResponse(
        {
          token,
          stored: false,
          error: "no KV namespace bound; hits are in observability logs only",
          hint: "wrangler kv namespace create OOB, then add the binding as OOB",
        },
        501
      );
    }
    const hits = (await env.OOB.get<OobHit[]>(`hits:${token}`, "json")) || [];
    logEntry({ ...log, event: "oob_query", token, count: hits.length } as never);
    return jsonResponse({ token, stored: true, count: hits.length, hits });
  }

  const found = extractToken(url);
  if (!found) return null;

  const hit = await buildHit(request, url, found.token, found.via);
  const stored = await recordHit(env, hit);

  // An <img> callback needs image bytes back or the browser reports an error,
  // which is visible to whoever is being tested.
  if (/\.(gif|png)$/i.test(url.pathname)) {
    return new Response(PIXEL, {
      headers: { "Content-Type": "image/gif", "Cache-Control": "no-store" },
    });
  }
  if (/\.js$/i.test(url.pathname)) {
    return new Response(`/* oob ${hit.token} received ${hit.ts} */\n`, {
      headers: { "Content-Type": "application/javascript", "Cache-Control": "no-store" },
    });
  }

  return jsonResponse({ ok: true, token: hit.token, via: hit.via, ts: hit.ts, stored });
}
